### ISSUE TITLE
AccessViolation GL.TexImage2D

### ISSUE THREAD

**Issue by xposure** [SFML/SFML.Net#114]
I've tried searching here and on the SFML forums for help here but I couldn't come up with anything. I get an access violation running the OpenGL example at the following code on TexImage2D.

            using (Image image = new Image("resources/texture.jpg"))
            {
                GL.GenTextures(1, out texture);
                GL.BindTexture(TextureTarget.Texture2D, texture);
                GL.TexImage2D(TextureTarget.Texture2D, 0, PixelInternalFormat.Rgba, (int)image.Size.X, (int)image.Size.Y, 0, PixelFormat.Rgba, PixelType.UnsignedByte, image.Pixels);
                GL.TexParameter(TextureTarget.Texture2D, TextureParameterName.TextureMagFilter, (int)TextureMagFilter.Linear);
                GL.TexParameter(TextureTarget.Texture2D, TextureParameterName.TextureMinFilter, (int)TextureMinFilter.Linear);
            }

*  I have copied all csfml 2.2 (I also tried 2.1 and 2.0) x86 DLLs to the project folder of OpenGL example since this is where its output directory is.
*  I have built the vs2008 solution so that all the DLLs are in lib/x86
*  I have OpenTK 1.1 installed and verified its being copied to the OpenGL output folder as expected. OpenTK DLL properties are 1.1.1599.6049.
*  I verified that Image.Pixels was loaded correctly with real data.
*  GenTextures is returning a valid value as well.

Not really sure what to do at this point, I haven't made any changes to anything code wise and just wanted to mess with the examples.

**Comment by xposure** [comment]
`GL.Clear(ClearBufferMask.ColorBufferBit | ClearBufferMask.DepthBufferBit);` is also giving an access violation. 

https://gist.github.com/xposure/c1ee616ab47859cb9cf3

Code expects the shaders to be in a subfolder "Shaders"

**Comment by xposure** [comment]
I've just downloaded and reinstalled OpenTK just for a sanity check and still get the same issue :/

**Comment by xposure** [comment]
One more odd thing to note, this works...

    GL.ClearDepth(0)

This fails with access violation

    GL.ClearColor(1,1,1,1);

**Comment by xposure** [comment]
Reproduced on 2 other machines (in fact, I haven't got it to work on a single pc). Since this works with init'ing normal OpenTK without SFML I'll leave this here for the smarter people to figure out.

*    OpenTK 1.1 installed on all machines
*    Checked out SFML.NET
*    Loaded the 2008 solution in to vs2013, built for x86
*    Dumped csfml 2.2 in to opengl directory
*    Access violation on TexImage2D and ClearColor

**Comment by zsbzsb** [comment]
I have been busy with the [SFML Game Jam](http://en.sfml-dev.org/forums/index.php?topic=18004.0) and also the tracker here is for confirmed issues. Hence the reason I have not responded.

What you need to do is open a forum thread with more details (you omit lots of information such as actual crash information).

**Comment by xposure** [comment]
Dropping this here because I don't plan to follow up on the forums or use SFML in my project due to these issues. Perhaps someone else will find use to it.

Thank you for taking the time to reply. Unfortunately I tried the examples on 2 more machines at work and they all throw the exact same exception on the same line. I have followed the instructions in the main README and simply can not get SFML to work. On the other hand, OpenTK  its self works on every machine I've tried it on, so I decided to scrap SFML and just use straight OpenTK. I now have reproduced this on 5 machines total and yet to get a single one to work.

To reiterate my attempts.
*  Installed OpenTK 1.1 from the OpenTK site.
*  Checked out SFML.NET project and loaded the solution in vs2013
*  Modified no code
*  Build the solution in vs2013 as x86 (tried x64 or 2 of 5 machines as well)
*  Downloaded CSFML x86 from http://www.sfml-dev.org/download/csfml/ - version 2.2
*  Downloaded SFML x86 from here http://www.sfml-dev.org/download.php tried both 2.2 and 2.3
*  Dropped all the DLLS in the OpenGL example folder since this is where the build drops the exe
![crash](https://cloud.githubusercontent.com/assets/6292318/7635693/542ae7c4-fa30-11e4-9745-bb5e447d7885.PNG)
*  I can reproduce this error on several different GL calls, not just the GenTexture2D
*  Debug output window has no useful information, so i'm not sure how much more information I can give you in regards to `actual crash information`. I see no log outputs in the OpenGL example folder as well.

Thanks
