### ISSUE TITLE
SFML.Graphics.PrimitiveType

### ISSUE THREAD

**Issue by xposure** [SFML/SFML.Net#115]
Is it possible to consider renaming this enum to something else? Its currently an ambiguous reference to OpenTK.Graphics.OpenGL.PrimitiveType which is used for describing the draw method.

EDIT: To be clear this throws an error for ambiguous reference when having a using statement for both OpenTK.Graphics.OpenGL and SFML.Graphics.

                GL.DrawArrays(PrimitiveType.Triangles, 0, 3);

**Comment by Rohansi** [comment]
It's annoying but renaming isn't a great solution. You should either use the [fully qualified name](https://msdn.microsoft.com/en-us/library/dfb3cx8s%28v=vs.71%29.aspx) or an [alias](https://msdn.microsoft.com/en-us/library/aa664765(v=vs.71).aspx) to deal with ambiguity.

**Comment by LaurentGomila** [comment]
Namespaces exist for a reason... which is certainly not to "using" them at global scope to cancel their effect ;)

**Comment by xposure** [comment]
Yea I realized after I sent this that it was most likely not an option since it would be a breaking change to everyone's code base.

I'll just mark it closed and live with it;)
