### ISSUE TITLE
Add XML doc to binary releases

### ISSUE THREAD

**Issue by FrankNiemeyer** [SFML/SFML.Net#117]
Neither the zip packages at http://www.sfml-dev.org/download/sfml.net nor the NuGet package (https://www.nuget.org/packages/SFML.Net) contain the XML documentation generated during build (doc\build). Consider adding those to the binary releases, so everyone gets full-fledged IntelliSense, including xml-doc-comments.

**Comment by zsbzsb** [comment]
I don't see why we couldn't add them, so lets do it for 2.3 release. But do we really need an issue for this?

**Comment by dabbertorres** [comment]
@LaurentGomila this can be closed too, via 09f8dd2a9f3b6e1153e4682bd19061fb4ebcb962
