### ISSUE TITLE
SFML.Window.Window.MouseButtonPressed not work

### ISSUE THREAD

**Issue by zwcloud** [SFML/SFML.Net#128]
I tried to make a dragable window with SFML, but it just won't invoke the  __MouseButtonPressed__ event handler.
https://gist.github.com/zwcloud/0c0e9f52d8010e1d5164
The break points set in event handler  __OnMouseButtonPressed__ and  __OnMouseMoved__ won't be hit when debugging. Instead, __MouseButtonRelease__ is called immediately I press the left mouse button (not released).

Using SFML2.2, VS2013 update4 community, .NET 4.5

**Comment by zsbzsb** [comment]
It sounds like you have mixed a newer version of CSFML with SFML.Net 2.2 as some internal event enums were extended between 2.2 and 2.3. Can you please verify that you have matching CSFML/SFML versions?

**Comment by zwcloud** [comment]
Oh.. Yes! the version of CSFML is 2.3 and SFML.NET is 2.2. I missed that.
Thank you!
