### ISSUE TITLE
RenderWindow to .Net's BitMap

### ISSUE THREAD

**Issue by Prakash19921206** [SFML/SFML.Net#140]
is it possible to copy output from SFML.Graphics.RenderWindow to  System.Drawing.Bitmap? 
try to display the output in pictureBox or like components.

**Comment by LaurentGomila** [comment]
You can update the content of a texture from a window with Texture.Update, and then retrieve the image with Texture.CopyToImage. And finally, you can get the raw pixel array with Image.Pixels.

Next time, please post your questions on the forum. This tracker is for confirmed bugs and tasks.
