### ISSUE TITLE
DLL mapping for SFML.net is not working in Linux

### ISSUE THREAD

**Issue by yashrk** [SFML/SFML.Net#145]
I have a latest official version of SFML.Net from the site (2.2, 64-bit) and a (C)SFML libraries installed from the Ubuntu repository. I have the following DLL mapping config:

```
<configuration>
    <dllmap dll="csfml-graphics-2" target="libcsfml-graphics.so.2"/>
    <dllmap dll="csfml-window-2" target="libcsfml-window.so.2.3"/>
</configuration
```

When trying to start a program I gen an error:

```
System.DllNotFoundException: libcsfml-graphics.so.2
  at at (wrapper managed-to-native) SFML.Graphics.RenderWindow:sfRenderWindow_createUnicode (SFML.Window.VideoMode,intptr,SFML.Window.Styles,SFML.Window.ContextSettings&)
  at SFML.Graphics.RenderWindow..ctor (SFML.Window.VideoMode mode, System.String title, SFML.Window.Styles style, SFML.Window.ContextSettings settings) [0x00043] in <7c7f42323ce84ef6957e114ed6eaff0f>:0
  at SFML.Graphics.RenderWindow..ctor (SFML.Window.VideoMode mode, System.String title) [0x0000b] in <7c7f42323ce84ef6957e114ed6eaff0f>:0
  at SFML.Net_Test.Program.Main () [0x00001] in /home/yashrk/src/education/csharp/SFML_01_simple_test/SFML_simple_test/Program.cs:14
```

I tried to add full path to `.so` files to DLL mapping files, with no luck.

Ubuntu 16.04, libcsfml version is 2.3-2build1.

**Comment by dabbertorres** [comment]
Do you have SFML library installed? CSFML depends on SFML.

**Comment by yashrk** [comment]
Yes, surely:
```
$ dpkg -L libsfml-graphics2.3v5
/.
/usr
/usr/share
/usr/share/doc
/usr/share/doc/libsfml-graphics2.3v5
/usr/share/doc/libsfml-graphics2.3v5/copyright
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/libsfml-graphics.so.2.3.2
/usr/share/doc/libsfml-graphics2.3v5/changelog.Debian.gz
/usr/lib/x86_64-linux-gnu/libsfml-graphics.so.2.3
```

**Comment by dabbertorres** [comment]
That's only the graphics module. You need the window and system modules.

If that package did not pull in the system module, it is incorrectly configured.
Since you're creating an SFML window, you need the window module as well.

**Comment by yashrk** [comment]
I have `libsfml-system2.3v5` and `libsfml-window2.3v5` packages installed too. Assemblies `sfmlnet-system-2`, `sfmlnet-window-2` and `sfmlnet-graphics-2` are added to references of my project.

**Comment by dabbertorres** [comment]
Is there a reason you are trying to manually map libraries?
Anecdotally, I've never needed to do so.

Maybe @Balnian @LaurentGomila can chime in?

**Comment by Balnian** [comment]
I think you need to do the maping because the csfml lib namings on Windows cannot be mapped directly to the Linux naming, it's the "-2" in windows dll name that's causing the problem, (same reason i couldn't use the .Net Core dllimport naming interpolation included).
But i never tried Sfml.Net with Mono on Linux so take this with a pinch of salt.
Also, try in your maping ".so" instead of ".so.2" (make sure it exist) and maybe try adding ".dll" in the Windows names? 
Worst case switch to .Net Core 2.0 and use the #143 PR, somebody tested it on Ubuntu, but you will need to compile the latest csfml yourself (i don't think/know if it's available yet from the Ubuntu repository)

**Comment by yashrk** [comment]
> Is there a reason you are trying to manually map libraries?

Without a mapping config Mono cannot find libcsfml, I get a `System.DllNotFoundException` for library `csfml-graphics-2`.

>  Also, try in your maping ".so" instead of ".so.2" (make sure it exist)

It exists. I get a `System.DllNotFoundException`. Full path to `.so` file doesn't help too.

> and maybe try adding ".dll" in the Windows names?

In that case Mono cannot find `csfml-graphics-2`.

**Comment by dabbertorres** [comment]
Isn't that just what you're getting now?

I haven't been able to reproduce.

Maybe for a reference, check out my [sfml.net ubuntu docker image](https://github.com/dabbertorres/sfml.net-docker/blob/master/Dockerfile). That works, I've built and run programs with it.

It builds from SFML.NET/master, but I did create symlinks for each csfml library: libcsfml-module-2.so

**Comment by yashrk** [comment]
I  probably found what was an issue: MonoDevelop is distributed through Flatpak, and Flatpak uses bubblewrap, kind of poor man's chroot. So MonoDevelop can not see system-wide libraries. I even successfully installed SFML shared libraries into MonoDevelop's "chroot", but there are still some issues (maybe ABI incompatibility), and without a possibility to even get a `strace` output the problem doesn't look solvable (maybe I will create a bug in MonoDevelop's bugtracker).

I'll close this issue, anyway; I will try to use plain Mono, without an IDE. Are there some open projects using SFML.Net to copy build configuration from?
