### ISSUE TITLE
I cannot create SFML.Audio.Music from existing Music

### ISSUE THREAD

**Issue by ProTheory8** [SFML/SFML.Net#148]
I cannot create SFML.Audio.Music from existing Music

```c#
using SFML.Audio;

// ...

Music music1 = new Music("C:\path\to\file.wav");

Music music2 = new Music(music1); // Don't work
```

**Comment by dsoronda** [comment]
```csharp
using SFML.Audio;
// ...
Music music1 = new Music("C:\path\to\file.wav");
Music music2 = new Music(music1); // Don't work
```
What should be expected result for music2 ?

I'm asking this regarding #151, how to set up test for this kind of errors?

**Comment by LaurentGomila** [comment]
Such a constructor doesn't exist.

**Comment by eXpl0it3r** [comment]
I don't see any reason why that constructor should be created.

If this is a wanted feature, then it might be good to provide some use cases and explanations.
