### ISSUE TITLE
SFML.Audio.Music System.DllNotFoundException

### ISSUE THREAD

**Issue by Editaw5X** [SFML/SFML.Net#149]
```c#
Music mainMenuTheme = new Music("path\to\mp3\file.mp3");
```
System.DllNotFoundException: "Unable to load DLL "csfml-audio-2""

![error](https://user-images.githubusercontent.com/24957968/34918595-b3881da2-f976-11e7-9149-e5df6d32f457.png)

**Comment by Editaw5X** [comment]
@LaurentGomila help

**Comment by Editaw5X** [comment]
@LaurentGomila @madpew @mantognini @eXpl0it3r @binary1248 
help

**Comment by LaurentGomila** [comment]
This kind of question is better answered on the forum, so let's close this issue since you've already opened a post there.

https://en.sfml-dev.org/forums/index.php?topic=23079.0
