### ISSUE TITLE
Update to 2.5

### ISSUE THREAD

**Issue by olivierLefebvre96** [SFML/SFML.Net#152]
Hello,
Could you update to SFML 2.5, please? 
Thank you :)

**Comment by LaurentGomila** [comment]
Who is "you"? Do you know who maintains SFML.Net? Did you check what happened last to SFML.Net? The latest discussions about its future?

And most of all, do you *really* think that opening an issue on the tracker will magically get the job done? Seriously.

**Comment by olivierLefebvre96** [comment]
I was just asking and no I didn't check what happened last.
I did like in this issue: https://github.com/SFML/SFML.Net/issues/132

Sorry.
