### ISSUE TITLE
Update nuget package and publish it on nuget.org

### ISSUE THREAD

**Issue by dsoronda** [SFML/SFML.Net#158]
It would be nice to publish newer version to nuget.org ( Netstandard version).

I was thinking to write some simple `how to start with SFML.net` tutorials and it would be nice that we have up to date nuget package.

Thanks

**Comment by yar1k0v** [comment]
Yo, any updates?

**Comment by LaurentGomila** [comment]
> Can we enable the wiki here on github?

Done.
