### ISSUE TITLE
Add Nuget Info to Readme

### ISSUE THREAD

**Issue by BenjaminHolland** [SFML/SFML.Net#161]
There are 31 different sfml packages on nuget. We should add links to the ones being built from this repository to the Readme to reduce confusion. It'd also be nice to have the nuget badges that show the current package version. If someone can clarify which nuget packages are part of this repo and which aren't I'd be glad to do it.

**Comment by eXpl0it3r** [comment]
I still like to improve the readme, but with #160 there's a link now.
