### ISSUE TITLE
SFML.Net 2.5 Nuget script doesn't work on VisualStudio

### ISSUE THREAD

**Issue by ramm32** [SFML/SFML.Net#163]
The official [website](https://www.sfml-dev.org/download/sfml.net/) encourages to use the latest version wich is only available via Nuget
I have installed the 11KB Nuget package (?) and though something was missing
then tried to run code and it doesnt detect any reference 
So how this works? I supose that I just ´Install-Package SFML.Net -Version 2.5.0´ in nuget and it will work out of the box right?
i don't get it why visual can't detect it?

![image](https://user-images.githubusercontent.com/33072667/59838298-5539ef80-9314-11e9-8b87-aa48759cf3a4.png)

**Comment by DemoXinMC** [comment]
Some more specific error messages than "it doesnt detect any references" would be super helpful here.

Most likely, you've run into the same issue that many others have, which is you have created a .NET Framework application rather than a .NET Core application.

**Comment by DemoXinMC** [comment]
Looking further at your issue, it appears that you have not installed the modern NuGet packages.  As of v2.5, SFML.NET was divided into its 4 separate modules

- SFML.System
- SFML.Window
- SFML.Graphic
- SFML.Audio

**Comment by DavDag** [comment]
To create a project you just need to install [.net sdk](https://dotnet.microsoft.com/download) (i suggest you 3.0 version) and run thoose two commads inside VS Code:

_dotnet new console.
dotnet add package SFML.Net --version 2.5.0._

Look at my repo to see an example project made using SFML.NET 2.5.
[this](https://github.com/DavDag/Csharp_Animated_MazeCreator)

**Comment by eXpl0it3r** [comment]
Installing the NuGet package [SFML.Net](https://www.nuget.org/packages/SFML.Net/) in a .Net Core or Standard 2 console project, works correctly.
As such, I'll close this issue.
