### ISSUE TITLE
ContextSettings Signature Mismatch (MarshalDirectiveException)

### ISSUE THREAD

**Issue by rfuge** [SFML/SFML.Net#166]
I just upgraded to SFML 2.5 and found attempting to read Settings property on a RenderWindow throws a MarshalDirectiveException with the message _Method's type signature is not PInvoke compatible_

Here's my code to reproduce.
```csharp
class Program
{
    static void Main(string[] args)
    {
        var running = true;
        using (var window = new RenderWindow(VideoMode.DesktopMode, "Test"))
	{
	    window.Closed += (sender, eventargs) => running = false;
            var settings = window.Settings;

            while (running)
	    {
	        window.WaitAndDispatchEvents();
		window.Clear();
		window.Display();
	     }
	}		
    }
}
```
I had a dive into the source and think this is because in CSFML the SRgbCapable member of ContextSettings is an sfBool which is Int32 and .NET is expecting a boolean.

**Comment by rfuge** [comment]
Just to test my conclusion I swapped out SRgbCapable in ContextSettings to be an Int instead of a bool and that resolves the issue.

@eXpl0it3r Where would be the incentive to fix this? Would ContextSettings struct be changed in CSFML or in SFML.Net?

**Comment by eXpl0it3r** [comment]
What's the underlying type in C++? If it's a mismatch between SFML and CSFML, fix it in CSFML. If it's a mismatch between CSFML and SFML.Net, fix it in SFML.Net.

**Comment by rfuge** [comment]
in both C++ and C# its bool and in C its sfBool (Int)

I see sfBool is used everywhere in place of bool in CSFML so I'd be unsure if changing it for this one instance would be desired.

**Comment by eXpl0it3r** [comment]
Ah I see. I'll have to investigate how to resolve this. It seems like for functions we simply use `bool` in the import statements, not sure if a similar thing can be done for ContextSettings struct.

**Comment by eXpl0it3r** [comment]
Should probably be able to do something with the `[MarshalAs(...)]` attribute on the [SRgbCapable property](https://github.com/SFML/SFML.Net/blob/master/src/SFML.Window/ContextSettings.cs#L116).

**Comment by rfuge** [comment]
So I was expecting `[MarshalAs(UnmanagedType.Bool)]` described as a [4-byte boolean](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.unmanagedtype?view=netframework-4.8) to resolve this but I still get the the same exception for some reason.

**Comment by DemoXinMC** [comment]
@rfuge A quick look over things suggests that UnmanagedType.I4 would be the correct Marshal Type.  If you're already set up to test it, give that a whack and let us know if it resolves it.  If not, I can check shortly myself.

**Comment by rfuge** [comment]
It really doesn't like that one and I got a different exception this time. 
> System.TypeLoadException: 'Cannot marshal field 'SRgbCapable' of type 'SFML.Window.ContextSettings': Invalid managed/unmanaged type combination (booleans must be paired with I1, U1, Bool, or VariantBool).'

From that error I tried both I1 and U1 too though I don't think they would make sense anyway, they don't work either.

**Comment by rfuge** [comment]
I'm wondering if this might be soley down to the discrepancy in the size of the structs between CSFML and SFML.Net, given that swapping out the bool with a Int in SFML.Net resolves the issue.

**Comment by DemoXinMC** [comment]
Oh, almost definitely.  Just trying to think what might be the best way to resolve it.  Switching to int is a solution, but it's not pretty, so before I agree to make that switch, I want to evaluate other possible answers.

**Comment by DemoXinMC** [comment]
Specifically, System.Boolean is not a blittable type within a struct, thereby making the struct non-blittable, meaning that the marshaler can't deal with it.

**Comment by rfuge** [comment]
The only other solution I can think of without swapping the field type or changing CSFML is to add a new type to SFML.Net to reflect the C counterpart if it seems necessary... like a IntBool type.

**Comment by DemoXinMC** [comment]
I'm not able to replicate the change to int solving the exception.

**Comment by rfuge** [comment]
I'm testing with a .NET Core app with SFML in as local dependencies.

All I've changed is [SRgbCapable](https://github.com/SFML/SFML.Net/blob/master/src/SFML.Window/ContextSettings.cs#L116) from `bool` to `int` and in the constructor

`SRgbCapable = sRgbCapable ? 1 : 0;`

My big project I upgraded is a .NET Framework app and that also works with this change.

**Comment by DemoXinMC** [comment]
I had something derpy going on with my build setup before.  I've implement the int conversion + a property called sRGBCapable in PR #167

**Comment by LaurentGomila** [comment]
Fixed by #168

**Comment by CoolDadTx** [comment]
This was resolved 3 months ago but I don't see that any release has been done since then to get this to NuGet so we can use it. How can we get the fix without having to build and ship the library ourselves?

**Comment by just-ero** [comment]
This appears fixed in recent versions.

However, crucially, `master` currently declares `SRgbCapable` like this:
https://github.com/SFML/SFML.Net/blob/58bdbb9c977a1d3b9a58c73933afbc4986c53d87/src/SFML.Window/ContextSettings.cs#L114-L115
The above declaration is incorrect and will break in big endian contexts.

**Comment by just-ero** [comment]
Sorry for the false alarm.

I see that `2.6.0` changed `sfContextSettings.sRgbCapable` to `bool` from the previous `sfBool`.
