### ISSUE TITLE
Cannot update Music properties

### ISSUE THREAD

**Issue by rkBrunecz** [SFML/SFML.Net#171]
Hi all!

Long time user of SFML, and just recently started using the .Net bindings. Recently, I've been having some issues with properties of the Music object not being set for some reason, and I am really not sure why. Here is some of my code:

```
public uint Play(MusicSettings settings, string filePath)
        {
            MusicComponent component = new MusicComponent()
            {
                Music = new Music(filePath),
                Id = _songId++
            };

            component.Music.SetSettings(settings);
            
            component.Music.Play();

            _music.AddLast(component);

            return _songId++;
        }
```

MusicComponent just contains an Id and the Music object, it does nothing else other than that.

Music.SetSettings is an extension method for just setting the different properties for the music object.

```
internal static void SetSettings(this Music music, MusicSettings settings)
        {
            music.Position = settings.Position;
            music.Volume = settings.Volume;
            music.Attenuation = settings.Attenuation;
            music.MinDistance = settings.MinDistance;
            music.Pitch = settings.Pitch;
            music.PlayingOffset = settings.PlayingOffset;
            music.RelativeToListener = settings.RelativeToListener;
            music.Loop = settings.Loop;
        }
```

MusicSettings is a simple struct. While running, I know the values in MusicSettings are coming through properly. But after setting the volume for the Music object, the volume does not reflect what is set in the MusicSettings struct. For some reason, all of the properties of the Music object are defaulting to 0. And I know the file is loading properly because I can see the sample rates, channel count, etc. 

Am I doing something wrong here? I am not seeing an errors logged in the output, neither.

**Comment by DemoXinMC** [comment]
Can you submit a minimal example for this so I can work out what's going on?

**Comment by rkBrunecz** [comment]
I figured out the issue while creating a minimal example. It turns out that I had too many sound objects, and that was causing issues with the music objects. Sorry about creating an issue for such a silly mistake!
