### ISSUE TITLE
window.PollEvents is not public forcing inheritance.

### ISSUE THREAD

**Issue by Shadowblitz16** [SFML/SFML.Net#173]
what the title says.
it would be nice if I didn't have to inherit the Sfml.Window so I can control when its shown

**Comment by DemoXinMC** [comment]
Window.DispatchEvents() is the appropriate call.  You should not be manually iterating events, binding to the supplied Events instead.

**Comment by Shadowblitz16** [comment]
can you provide a example?
I am just following the way c++ sfml does it

**Comment by DemoXinMC** [comment]
There's an entire example folder available in the repo, but here's a specific example for using the events.
https://github.com/SFML/SFML.Net/blob/master/examples/window/Program.cs

**Comment by eXpl0it3r** [comment]
SFML.Net has a few .net specific approaches, thus not everything translates directly from C++ to C#.
Make sure to check out the examples as @DemoXinMC already mentioned.
