### ISSUE TITLE
Transform.Translate does nothing

### ISSUE THREAD

**Issue by RoyAwesome** [SFML/SFML.Net#175]
I'm using Core 3.1 Preview

The following code does nothing

`Transform tf = new Transform();
            tf.Translate(100, 100);`

![image](https://user-images.githubusercontent.com/455800/69834455-5e968480-11ef-11ea-95f3-536e769b996b.png)

![image](https://user-images.githubusercontent.com/455800/69834468-6e15cd80-11ef-11ea-95ed-7ef67add6e83.png)

I expect the transform matrix to change when I translate it.  This could be a core bug, but I'm not sure with Translate calling into native code.  

For what it's worth, Scale and Rotate also do nothing.  I just don't have a good test case for it.

**Comment by Rohansi** [comment]
This is going to be because the compiler is doing some defensive copies. Making the struct `readonly` might fix it (see [this](https://blog.jetbrains.com/dotnet/2018/05/10/readonly-structs-ref-readonly-conditional-ref-expressions-c-7-2-rider-resharper/)) but, even if it works, this is just a bad API design. Structs should almost always be immutable and just return the modified instance. Being readonly (including using that new modifier) will open up more optimizations than mutating the struct.

**Comment by eXpl0it3r** [comment]
> the compiler is doing some defensive copies. Making the struct readonly might fix it

Which struct are you referring to exactly?

Reading the [CSFML code](https://github.com/SFML/CSFML/blob/master/src/SFML/Graphics/Transform.cpp#L144) the point seems to be that the struct is modifiable, so readonly wouldn't really work. But the [CSFML code](https://github.com/SFML/CSFML/blob/master/src/SFML/Graphics/ConvertTransform.hpp#L38) also create a completely new object, which seems to not properly translate back via ref struct to `this` assignment. 🤔

**Comment by Rohansi** [comment]
I was talking about the C# `Transform` struct. IMO it should be readonly and return the translated/scaled/etc instance instead. This is the recommended way to do things in C#.

**Comment by DangerRoss** [comment]
I can't recreate this issue... We sure this isn't because in the example the entire matrix is zero and therefore you're getting zero as the result? If you initialise with `Transform.Identity` for example you should see the values change.

**Comment by RoyAwesome** [comment]
@DangerRoss that would still be a bug because you would expect the above code to actually do something.

**Comment by RoyAwesome** [comment]
After testing, @DangerRoss 's workaround does not work for me.  Same behavior.

**Comment by DangerRoss** [comment]
hmm I don't know then.

![image](https://user-images.githubusercontent.com/44978772/69902125-d85e7780-1381-11ea-9fbe-0f61b7850484.png)

I've tried both .NET Core 3 and 3.1 preview with SFML from Nuget and a nonzero matrix changes for me, and a zero matrix does not. Makes me unsure if this issue is related to how the underlying API is handling Transform to CSFML even if it's not the recommended approach, as I wouldn't expect the values to change the behavior.

**Comment by RoyAwesome** [comment]
Ya know, I went and tested it again and it does work as you see.  I wonder why I got a bad test.  I probably chalk that up to me making a mistake.  It does do for me exactly what DangerRoss has posted.

**Comment by eXpl0it3r** [comment]
Ah, I didn't really think that far. Yes, a matrix of 0s should not change when you apply some transformation on it.

In C++ when you create a new instance of `sf::Transform`, we do actually create an identity matrix, which IMHO makes sense, as the "default" state of a matrix is its identity and not a null matrix.

@LaurentGomila should we change the constructor of the C# Transform class to return an identity matrix?

C#

```csharp
var transform = new Transform();
Console.Out.WriteLine(transform.ToString());
```

```
[Transform] Matrix(0, 0, 0,0, 0, 0,0, 0, 0, )
```

(Potentially also clean up the ToString() implementation)

C++

```cpp
auto transform = sf::Transform{};
std::cout << to_string(transform) << "\n"s; // Custom to_string function
```

```
Matrix [1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,]
```

**Comment by DangerRoss** [comment]
Keep in mind Transform is currently a struct and C# does not allow you to define a default constructor for structs.

**Comment by eXpl0it3r** [comment]
Ah, that explains then why it probably wasn't done so in the first place and the workaround is simple, just need to remember to use it: `var transform = Transform.Identity;`

I'll close this issue then for now.

**Comment by LaurentGomila** [comment]
Yep, it's a known limitation, and the workaround is indeed to initialize with `Transform.Identity`.

**Comment by RoyAwesome** [comment]
A comment or documentation note would be nice to prevent others from encountering this issue again :)

**Comment by eXpl0it3r** [comment]
Would you be willing to provide a PR with such an addition?
