### ISSUE TITLE
Transformable.Position must be field

### ISSUE THREAD

**Issue by PickGG** [SFML/SFML.Net#180]
![Снимок](https://user-images.githubusercontent.com/35164385/74340683-2d7a2900-4dc8-11ea-9153-6ad86ca87619.PNG)
An error occurs when I try to change the individual coordinate of a figure because the position is a property, it needs to be a field.
Error code is CS1612

**Comment by PickGG** [comment]
error code CS1612

**Comment by DangerRoss** [comment]
This is because Position is a struct. You need to use a local variable of Position to modify individual members.

```csharp
var rect = new RectangleShape();

var pos = rect.Position;

pos.X = 455.67;
pos.Y += 12424.67;

rec.Position = pos;
```

**Comment by LaurentGomila** [comment]
Don't forget that SFML.Net is a *binding*, not a native C# library.
