### ISSUE TITLE
No release for .NET Core 3.0

### ISSUE THREAD

**Issue by ashleydavies** [SFML/SFML.Net#182]
Hi SFML.Net maintainers, thanks for making this!

It looks like SFML.Net supports .NET Core 3.0 (#172), and I was wondering if it would be possible to tag a release and roll it out to Nuget?

Happy to help in any way I can!

**Comment by ashleydavies** [comment]
My apologies if I'm being ignorant here and the current package should support .NET Core 3; I may have jumped to the wrong conclusion too hastily when my project stopped building (DLL not found) after upgrading to .NET Core 3.0.

**Comment by DemoXinMC** [comment]
The current NuGet packages work for Core 3.0.

A new tag will bring in some bugfixee, and build the library against the
Core 3.0 compiler which will yield some small performance gains.

I personally would like the chance to push new versions of VertexArray and
Time before we tag a new release, though I'm not sure what other goals
others may have before a new tag is created.

**Comment by ashleydavies** [comment]
Whoops 😅 I must be doing something silly on my side, apologies!

Happy to leave this issue open if it helps to host the discussion you mentioned, though.

**Comment by eXpl0it3r** [comment]
Fixing the open bugs on CSFML side would be great, but I also don't mind releasing a new version earlier. Either way, we first need a new CSFML release, as that also brings in quite a few fixes.

**Comment by eXpl0it3r** [comment]
Don't think we really need this issue, to track progress, so I'll close it for now. Feel free to keep discussing things though 🙂
