### ISSUE TITLE
[ Suggestion ] Add F# samples

### ISSUE THREAD

**Issue by FoggyFinder** [SFML/SFML.Net#186]

**Comment by eXpl0it3r** [comment]
I don't have any experience whatsoever with F#, as such I'm unable to provide such an example.
Can you provide such an example or know someone who can?

**Comment by FoggyFinder** [comment]
I'll can try to do it tomorrow

**Comment by eXpl0it3r** [comment]
I guess there's always a next tomorrow 😉 

I'm closing this for now, as there hasn't been any additional interest. If you do come up with an example, feel free to directly open a pull request.
