### ISSUE TITLE
Problem with mkbundle if you use --simple --library libcsfml-(XXXX).so than bundled executable can't show background and shapes

### ISSUE THREAD

**Issue by DeafMan1983** [SFML/SFML.Net#198]
Hello everyone,

I have found bug if I want bundle into mono bundled executable with mkbundle on Ubuntu 18.04
`mkbundle --simple --cross mono-5.20.1-ubuntu-16.04-x64 SFML_Test.exe --library libcsfml-audio.so --library libsfml-audio.so --library libcsfml-graphics.so --library libsfml-graphics.so --library libcsfml-system.so --library libsfml-system.so --library libcsfml-window.so --library libsfml-window.so -o SFML_Test -v`
Result:
![image](https://user-images.githubusercontent.com/57066679/110208756-49e07c00-7e89-11eb-8c93-20de68116d9c.png)

Wordaround: without libcsfml-(XXXX).so into bundled executable
`mkbundle --simple --cross mono-5.20.1-ubuntu-16.04-x64 SFML_Test.exe --library libsfml-audio.so --library libsfml-graphics.so --library libsfml-system.so --library libsfml-window.so -o SFML_Test -v`
Result:
![image](https://user-images.githubusercontent.com/57066679/110208817-9f1c8d80-7e89-11eb-850c-b5a42feb8a0e.png)

PS: Please fix normal extern "C" { ... } for public methods of library so for Linux, dll for Windows and dylib for MacOS 10.1x

But I am surprised because you force against `objdump -TC libsfml-(XXXX).so` But I can't get public methods from libsfml-(XXXX).so - I understand but it is not SF::CreateWindow() and It should be sf_create_window(void* handle) for example. 

Thanks!

**Comment by eXpl0it3r** [comment]
Can you describe a bit more what you think needs changing?

I don't know `mkbundle` and don't fully understand why CSFML seems to cause issues when it's bundled.

CSFML is just a C interface for the C++ SFML library.

**Comment by DeafMan1983** [comment]
mkbundle is makebundle of Mono Project ( C#. Visual Basic and F# for Linux and MacOS successor of Net Frameworks for Windows. See www.mono-project.com and Github has also https://github.com/mono/mono

csfml-(XXXX).so bundle into mono bundled executable but shapes and backgrounds don't show up since SFML Window if it is already running. 

Sorry my bad English. I am German.

**Comment by eXpl0it3r** [comment]
With native dotnet support, having just updated CSFML as well as SFML.Net, and not really wanting to investigate some bundling behavior. I'll close this issue for now.

Make sure to try the latest SFML.Net / CSFML package and see if the issue persists.
