### ISSUE TITLE
Add font smoothing

### ISSUE THREAD

**Issue by G3Kappa** [SFML/SFML.Net#200]
See: https://github.com/SFML/SFML/pull/1690

**Comment by DemoXinMC** [comment]
SFML.NET does not currently attempt to maintain itself against the in-dev stuff in SFML.  Once 2.6 is released, SFML.NET can be updated with the new features in it.

**Comment by G3Kappa** [comment]
Ah, sorry! Thank you for clearing that up. I will patiently wait, then :)
