### ISSUE TITLE
Interfaces do not follow C#'s naming convention. 

### ISSUE THREAD

**Issue by TheVeryStarlk** [SFML/SFML.Net#204]
Prefixing interfaces names with an `I` in C# is a recommended convention according to [MS docs](<https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-classes-structs-and-interfaces>). I can try to make a pull request that has changes that comply with C#'s naming conventions, but I'm afraid it will break old/existing code in other SFML.NET projects. ☺️

**Comment by Marioalexsan** [comment]
Should be fixed as part of #271 for SFML.Net 3.
