### ISSUE TITLE
RenderTexture Display Method Return Incorrect Type

### ISSUE THREAD

**Issue by Rosst0pher** [SFML/SFML.Net#211]
sfRenderTexture_display return type disparity with CSFML.

sfRenderTexture_display currently returns `bool` and supposed to return `void`.

**Comment by eXpl0it3r** [comment]
Was this fixed? I can't seem to find what you're mentioning.

CSFML

https://github.com/SFML/CSFML/blame/d270e9a513094176bccc104865f20bdd2e9679e7/include/SFML/Graphics/RenderTexture.h#L105

SFML.Net

https://github.com/SFML/SFML.Net/blame/45b5a817e0ca753883237ce310a8f5ea3483af7a/src/SFML.Graphics/RenderTexture.cs#L290

I'll close this for now, if you still see an issue, feel free to reopen it. 🙂

**Comment by Rosst0pher** [comment]
Hey @eXpl0it3r hope all is well

I just double checked what I raised here and can confirm this is still an issue if you check the pinvoke method which doesn't match CSFML return type. 

https://github.com/SFML/SFML.Net/blob/master/src/SFML.Graphics/RenderTexture.cs#L554

https://github.com/SFML/CSFML/blob/master/include/SFML/Graphics/RenderTexture.h#L105

I haven't been active around SFML for some time now and unfortunately no longer have an environemnt setup to quickly fix this minor issue 😔I also don't see a reopen option, only to create a new one.

**Comment by eXpl0it3r** [comment]
Ahh! I was looking at the function signature and not the pInvoke signature. Thanks for pointing me in the right direction.
I'll re-open it then. Feel free to provide a fix for 🙂
