### ISSUE TITLE
GLSL Bool Vector Types Maybe Mismatched With CSFML

### ISSUE THREAD

**Issue by DangerRoss** [SFML/SFML.Net#213]
The following PInvoke methods use the bool vector types and I believe won't actually work.

- sfShader_setBvec2Uniform
- sfShader_setBvec3Uniform
- sfShader_setBvec4Uniform

All Bvec types in C# use `bool` which is 1-byte and in CSFML they are `sfBool` which is 4-bytes. While this has never noted to be a problem with `bool` pinvoke parameters, it has been an issue in the past for data structures #166. I haven't used shaders in SFML.Net so I haven't confirmed this but i'm pretty confident its an issue.

**Comment by Radix-Comet** [comment]
Just tested it, it works as expected.
![image](https://user-images.githubusercontent.com/104397149/171524404-8f4bafd3-f30f-44ef-8603-411baa1f0fd5.png)

**Comment by Radix-Comet** [comment]
Just tested it, yes it is an issue. I'm working on a fix right now

**Comment by eXpl0it3r** [comment]
Fixed with #217
