### ISSUE TITLE
Potentially Missing API Features

### ISSUE THREAD

**Issue by DangerRoss** [SFML/SFML.Net#215]
Setting a uniform color parameter is missing on Shader.
- sfShader_setColorUniform is missing in SFML.Net, obsolete Set color parameter is still present.

Bind method for VertexBuffer is missing and probably limits use cases with raw OpenGL calls
- sfVertexBuffer_bind is not defined in SFML.Net

**Comment by eXpl0it3r** [comment]
Fixed with #216
