### ISSUE TITLE
Error: Failed to load sound buffer: unsupported number of channels

### ISSUE THREAD

**Issue by joreg** [SFML/SFML.Net#221]
hello,

i'm getting the following error when using the SoundBufferRecorder on a raspberry pi 3b: 

```
Failed to load sound buffer (unsupported number of channels: 2126894056)
Unhandled exception. SFML.LoadingFailedException: Failed to load sound buffer from memory
   at SFML.Audio.SoundBuffer..ctor(Int16[] samples, UInt32 channelCount, UInt32 sampleRate)
   at SFML.Audio.SoundBufferRecorder.OnStop()
```

odd thing: the same app runs on windows without that problem. 

i even explicitly set the channel count of the SoundRecorder to 1 before starting recording.

any ideas?

**Comment by eXpl0it3r** [comment]
What version of SFML.Net and CSFML are you using?

**Comment by joreg** [comment]
right, so this happens with SFML.NET 2.5.0 and for CSFML i have these installed:

![grafik](https://user-images.githubusercontent.com/1067952/201066300-033f5940-45b6-4b5d-9939-942157036a08.png)
(not sure how to read that version number. is that 2.5 or 2.5.1?

**Comment by joreg** [comment]
@eXpl0it3r any thoughts what i could test?

**Comment by joreg** [comment]
progress: turns out it works if i build SFML.Audio.dll from latest sources. just the current nuget (2.5.0) is broken.

looks like the 2.5.0 nuget is over 3 years old. is there a reason there is no newer release?

**Comment by eXpl0it3r** [comment]
Good to hear. Not exactly sure which part cause the failure. We did fix some DLLImport mismatches, so maybe one of those caused the issue on your side.

Been meaning to publish a new CSFML version and then update the SFML.Net version, but it takes time to generate all the necessary binaries. Hopefully will get around to it soon.

**Comment by eXpl0it3r** [comment]
With the [new 2.5.1 version published](https://www.nuget.org/packages/SFML.Net/2.5.1), I'll assume this issue has been resolved and as such I'll close the issue.
If you still have trouble with the latest SFML.Net version, feel free to reopen this issue.
