### ISSUE TITLE
Sprite.Transform.Rotate does nothing

### ISSUE THREAD

**Issue by GDenisC** [SFML/SFML.Net#227]
SFML.Net Version: 2.5.0

Example:
```cs
spr.Transform.Rotate(value, CenterPosition);
```
note: Sprite.Rotation works, but it doesnt support rotation by center

**P.S.** all methods of Transform not works

**Comment by eXpl0it3r** [comment]
You shouldn't be modifying the Transform inside a Sprite directly.
If you want to apply a transformation to a sprite, then you can either apply it, by passing it to the Draw() function as RenderState or applying each transformation with the available methods (rotate, scale, move).

Note that transformations always happen around the origin point. So if you want to rotate by the center, you can also (temporarily) set the origin point to be the center of the sprite.
