### ISSUE TITLE
Add version restriction for CSFML

### ISSUE THREAD

**Issue by eXpl0it3r** [SFML/SFML.Net#255]
Nuspec allows for limiting version usages, so issues like #245 can't happen again.

The goal would be to lock SFML.Net X.Y.Z with CSFML X.Y so people were prevented from say installing CSFML 2.6 while using SFML.Net 2.5.1 causing potential breakage.

https://learn.microsoft.com/en-us/nuget/concepts/package-versioning?tabs=semver20sort

**Comment by Marioalexsan** [comment]
I'm not sure if this is possible given that applications can override the versions of packages used by dependencies:
<https://learn.microsoft.com/en-us/nuget/concepts/dependency-resolution#direct-dependency-wins>
