### ISSUE TITLE
'RenderWindow' does not contain a definition for pollEvent

### ISSUE THREAD

**Issue by poisonHornGames** [SFML/SFML.Net#264]

**Comment by DemoXinMC** [comment]
It's not supposed to.  Use `.DispatchEvents()`

**Comment by eXpl0it3r** [comment]
As @DemoXinMC you should use `DispatchEvents()`.

```csharp
while (window.IsOpen)
{
    window.DispatchEvents();
    window.Clear();
    window.Display();
}
```

See the complete [example](https://github.com/SFML/SFML.Net/blob/master/examples/netcore/Program.cs).
