### ISSUE TITLE
Consider adding support for tuples into Vector2f, Vector2i, Vector2u, Vector3f

### ISSUE THREAD

**Issue by jantajov** [SFML/SFML.Net#267]
Hi,

Currently it is not possible to deconstruct any vector to tuple
`var (x, y) = new Vector2f(1f, 1f);`

Nor is it possible to implicitly convert tuple to vector
`Vector2f scale = (1f, 1f);`

Would it be possible for you to add deconstruct method and implicit conversion operator to your vector classes? Tuples were introduced way back in [C# 7.0](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/value-tuples)

**Comment by eXpl0it3r** [comment]
Thank you for bringing this up, it will be added with SFML.Net 2.6.2
