### ISSUE TITLE
Let the CLR know how much memory you use

### ISSUE THREAD

**Issue by Oberon00** [SFML/SFML.Net#5]
Currently the garbage collector thinks that e.g. an Image is just the size of one IntPtr big, although it might occupy several MBs of memory. This is not optimal. You can read the following in the [MSDN Library](http://msdn.microsoft.com/en-us/library/system.gc.addmemorypressure.aspx#remarksToggle):

> In determining when to schedule garbage collection, the runtime takes into account how much managed memory is
> allocated. If a small managed object allocates a large amount of unmanaged memory, the runtime takes into account only the
> managed memory, and thus underestimates the urgency of scheduling garbage collection.

To solve this problem you should use [GC.AddMemoryPressure](http://msdn.microsoft.com/en-us/library/system.gc.addmemorypressure.aspx) (and of course [GC.RemoveMemoryPressure](http://msdn.microsoft.com/en-us/library/system.gc.removememorypressure.aspx)).

**Comment by zsbzsb** [comment]
@LaurentGomila Any idea how we are supposed to know how much memory everything takes? I would work on this, but for non trivial classes there is no way for us to know how much memory some classes are using. ```sf::Image``` is easy as we would multiple x*y*4, but for ```sf::CircleShape``` and ```sf::Texture``` (which uses VRAM).

**Comment by LaurentGomila** [comment]
I have no idea. Things allocated in VRAM shouldn't concern the GC, but for 3rd-party libraries (freetype, ...) it will be very difficult, it not impossible, to know how much memory is allocated by SFML objects.

**Comment by zsbzsb** [comment]
I have to agree that it seems very much impossible, and it is already established that users should explicitly dispose objects when they are finished with them (standard practice for IDisposable interface). I am going to close this because I don't think there is anyway to do this.
